### ISSUE TITLE
Cache readability

### ISSUE THREAD

**Issue by szepeviktor** [bueltge/Debug-Objects#38]
Please consider adding:

``` css
#cache .root ul {
    border-left: 1px dotted #808080;
    padding-left: 30px;
}
```
